### PR TITLE
Updated to 1.9

### PR DESCRIPTION
**Pull request by Cloman**
Bug Fixes

### CODE REVIEW

**Comment by rogermb** [comment]
Merged.

Some of the formatting was off, so I had to squash your commit while merging. Unfortunately, this has completely screwed up your merge, which is why a) your commit doesn't show up in the history and b) this pull request wasn't marked as "merged" automatically.

If point a) is an issue for you, I can roll this change back, redo the merge and do a force push. Or is this version okay for you?

**Comment by rogermb** [comment]
The Git gods seem to be angry with me.

I force pushed a fixed version, which automatically marked this PR as merged. Now there's a commit which shows you as the author but somehow isn't linked to your profile. :stuck_out_tongue:

**Comment by Cloman** [comment]
thats ok everyone likes to do stuff on their own way as long as the results are the same and has no performance inpact.

Didnt do it for the credits but for the know how as i never worked with git XD.
And ofcourse the few peeps on bukkit dev who are eager to use this.
So hope you can push it out to a release on the bukkit dev so the hand full of users have easy access.

**Comment by rogermb** [comment]
Will do! There's already a build available on the [build server](http://ci.stutzfam.ch/job/BukkitSpeak/240/).

I'll still have to test that build before I do a proper release, though. I don't have a Spigot server set up yet though, which means this will take quite some time...

EDIT: Can one actually download Spigot binaries again now? Or do they still contain the DMCA'd CraftBukkit code?

**Comment by Cloman** [comment]
dont worry.
Here you go.
This one i use atm in my live server.
<removed Link>

But if you want to make it your self you need spigot buildtools.jar but takes some more time and setup.

**Comment by rogermb** [comment]
Thank you! :D

**Comment by rogermb** [comment]
But really, I'm dumbfounded about why Spigot would make such a change which breaks almost every single plugin without providing some sort of backward compatibility method like Bukkit always used to.

**Comment by Cloman** [comment]
i think its more depend what source the minecraft it self had.
if it breaks more to be compatible just dont do it and go with the flow.
But it was already announced this was comming since 1.8  to 1.8.8 so it wasnt done in silence.

**Comment by rogermb** [comment]
And done, both versions should be available on dev.bukkit.org shortly (as soon as the files are approved by the staff).

For one second, I thought I had messed up. You know, there's a file called `plugin.yml` which should contain the current plugin version. And I had completely forgot to update that file. But then I checked out that file and realized that I had replaced the static version with one that is automatically inserted by maven when the plugin is built. Whew! :yum:

**Comment by Cloman** [comment]
Nice :)
And well have Happy bukkit campers again :)

**Pull request merged**
